# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'YSAP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

  # Pods for YSAP

  target 'YSAPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YSAPUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Alamofire', '~> 4.4'


end
